[project]
name = "energy-analytics-report"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.1",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
]
